const products= [
    { id: 1, name: "Kit compostaje básico", category: "Starter Kits", price: 14000, image: "assets/images/product-1.png", stock: 20, description: "Ideal para comenzar a compostar en casa de forma simple y sin experiencia previa. Este kit incluye todo lo necesario para transformar tus residuos orgánicos en abono natural, reduciendo tu basura y cuidando el planeta desde el primer día. Qué incluye: 	•	Compostera doméstica pequeña •Aireador manual •Filtro de carbón •Guía rápida de inicio" },
    { id: 2, name: "Kit compostaje urbano", category: "Starter Kits", price: 14000, image: "assets/images/product-2.png", stock: 20, description: "Diseñado especialmente para departamentos y espacios reducidos. Permite compostar sin olores ni desorden, integrándose fácilmente a tu cocina o balcón. Perfecto para un estilo de vida sustentable en la ciudad." },
    { id: 3, name: "Sensor de humedad", category: "Tecnología", price: 14000, image: "assets/images/product-3.png", stock: 20, description: "Permite controlar el nivel de humedad del compost para asegurar un proceso eficiente y saludable. Evita que los residuos se sequen o se saturen de agua, ayudando a obtener abono de mejor calidad." },
    { id: 4, name: "Sensor de temperatura", category: "Tecnología", price: 14000, image: "assets/images/product-4.png", stock: 20, description: "Mide la temperatura interna del compost para verificar que el proceso biológico esté activo. Fundamental para quienes buscan optimizar tiempos y resultados en la descomposición de residuos orgánicos." },
    { id: 5, name: "Compostera doméstica (bin)", category: "Accesorios", price: 14000, image: "assets/images/product-5.png", stock: 20, description: "Contenedor resistente y ventilado para compostaje doméstico. Diseñado para reducir olores y facilitar el manejo de residuos orgánicos, ideal para hogares que desean adoptar hábitos más sostenibles." },
    { id: 6, name: "Aireador", category: "Accesorios", price: 14000, image: "assets/images/product-6.png", stock: 20, description: "Herramienta manual que permite oxigenar el compost fácilmente. Al remover los materiales se acelera la descomposición y se previenen malos olores." },
    { id: 7, name: "Balde de residuos orgánicos", category: "Accesorios", price: 14000, image: "assets/images/product-7.png", stock: 20, description: "Recipiente práctico para recolectar restos de comida antes de llevarlos a la compostera. Cuenta con tapa hermética para evitar olores y mantener la higiene en la cocina." },
    { id: 8, name: "Filtro de carbón anti olores", category: "Accesorios", price: 15000, image: "assets/images/product-8.png", stock: 20, description: "Filtro reemplazable de carbón activado que neutraliza olores y ayuda a mantener un ambiente limpio. Compatible con la mayoría de composteras domésticas." },
    { id: 9, name: "Guía digital", category: "Educación", price: 14000, image: "assets/images/product-9.png", stock: 20, description: "Guía completa para aprender a compostar desde cero. Incluye instrucciones claras, recomendaciones prácticas y soluciones a los errores más comunes, ideal para principiantes y entusiastas del hogar sostenible." },
    { id: 10, name: "Curso a domicilio", category: "Educación", price: 14000, image: "assets/images/product-10.png", stock: 20, description: "Servicio personalizado en tu hogar para aprender a compostar de manera correcta. Un especialista te guiará paso a paso, adaptando el sistema a tu espacio y necesidades para asegurar resultados exitosos." },
]
